name: filebeat

filebeat.prospectors:
- type: log
  paths:
    - /var/log/*.log
- type: log
  paths: /var/log/osquery/osqueryd.*.log
  json.keys_under_root: true
  json.add_error_key: true
  
output.elasticsearch:
  hosts: ["YOURELASTICIP:9200"]